import json
import os
import struct
import sys

# Dynamic language handling via CLI arguments (--lang=Spanish)
# Example: python patch_global-metadata.dat.py in.dat out.dat --lang=French
LANG_NAME = "French"
for arg in sys.argv:
    if arg.startswith("--lang="):
        LANG_NAME = arg.split("=", 1)[1]

# Path to the identifier protection JSON generated by diff_metadata.py (hardcoded in the script's root directory)
PROTECTION_FILE = r"./protected-identifiers.json"

MOD = r"./PvZ_Fusion_Translator"
TRANS = r"./Translations"
DIR_EN = os.path.join(MOD, "Localization", "English")
DIR_LANG = os.path.join(MOD, "Localization", LANG_NAME)
DIR_LANG2 = os.path.join(TRANS, LANG_NAME, "global-metadata")


def LJ(p):
    try:
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


# ---------------- PROTECTION ----------------
def load_protection(path):
    """
    Loads the JSON generated by diff_metadata.py.
    Returns {position(literal index): bytes_value}.
    Protection is strictly position -> value (no value-only protection,
    to avoid blocking legitimate translations of the same text elsewhere).
    """
    data = LJ(path)
    if not data or not data.get("protected"):
        print(f"[!] Protection JSON missing, unreadable, or empty: {path}")
        print("    Place protected-identifiers.json in the root directory (next to the script), generated by diff_metadata.py.")
        sys.exit(1)
    by_index = {}
    for e in data["protected"]:
        by_index[e["index"]] = bytes.fromhex(e["value_hex"])
    print(f"Protection: {len(by_index)} pairs (position, value)")
    return by_index


def read_literals(buf, npairs_hint=None):
    """Reads all literals from a metadata buffer: list of bytes, indexed by position."""
    slOff = struct.unpack_from("<I", buf, 8)[0]
    npairs = (slOff - 8) // 8
    pairs = [struct.unpack_from("<II", buf, 8 + i * 8) for i in range(npairs)]
    sldOff = pairs[1][0]
    n = pairs[0][1] // 8
    out = []
    for i in range(n):
        length, di = struct.unpack_from("<II", buf, slOff + i * 8)
        out.append(bytes(buf[sldOff + di: sldOff + di + length]))
    return out


def check_protection(lits, prot):
    """Returns the list of protected positions whose values no longer match."""
    return [i for i, v in prot.items() if i >= len(lits) or lits[i] != v]


# ---------------- DICTIONARY BUILDING EN -> CN -> LANG ----------------
def build_dict():
    en_to_lang = {}
    
    def add(en, lang):
        if isinstance(en, str) and isinstance(lang, str) and lang.strip() and en != lang:
            en_to_lang[en] = lang

    def add_pivot(cn_to_en_dict, cn_to_lang_dict):
        if not cn_to_en_dict or not cn_to_lang_dict:
            return
        # Invert CN -> EN to EN -> CN
        en_to_cn = {}
        for cn, en in cn_to_en_dict.items():
            if isinstance(cn, str) and isinstance(en, str) and en.strip():
                en_to_cn[en] = cn

        # Resolution EN -> CN -> LANG
        for en, cn in en_to_cn.items():
            lang = cn_to_lang_dict.get(cn)
            # Only add if translation exists and is different from English
            if isinstance(lang, str) and lang.strip() and lang != en:
                en_to_lang[en] = lang

    # 1. Generic strings
    ts_en = LJ(os.path.join(DIR_EN, "Strings", "translation_strings.json")) or {}
    ts_lang = LJ(os.path.join(DIR_LANG, "Strings", "translation_strings.json")) or {}
    add_pivot(ts_en, ts_lang)

    # 2. Tips
    for f in ("tips_fs", "tips_iz"):
        ent = LJ(os.path.join(DIR_EN, "Strings", f"{f}.json")) or {}
        langt = LJ(os.path.join(DIR_LANG, "Strings", f"{f}.json")) or {}
        add_pivot(ent, langt)

    # 3. Buffs / Modifiers (Reconstructing Name + Desc)
    cnb = LJ(os.path.join(MOD, "Dumps", "travel_buffs.json")) or {}
    enb = LJ(os.path.join(DIR_EN, "Strings", "travel_buffs.json")) or {}
    langb = LJ(os.path.join(DIR_LANG, "Strings", "travel_buffs.json")) or {}

    for cat in cnb:
        if not isinstance(cnb[cat], dict):
            continue
        for bid, cbuff in cnb[cat].items():
            ebuff = enb.get(cat, {}).get(bid)
            langbuff = langb.get(cat, {}).get(bid)
            if not isinstance(ebuff, dict) or not isinstance(langbuff, dict):
                continue

            # Process names
            en_name = ebuff.get("name")
            lang_name = langbuff.get("name")
            if en_name and lang_name and en_name != lang_name:
                en_to_lang[en_name] = lang_name

            # Process descriptions
            en_desc = ebuff.get("desc")
            lang_desc = langbuff.get("desc")
            if en_desc and lang_desc:
                en_full = (f"{en_name}: " if en_name else "") + en_desc
                lang_full = (f"{lang_name}: " if lang_name else "") + lang_desc
                if en_full != lang_full:
                    en_to_lang[en_full] = lang_full
                    
    # --- Interface & UI Translations (Direct EN -> Target) ---
    json_path = os.path.join(DIR_LANG2, "metadata.json")
    if os.path.isfile(json_path):
        ui_data = LJ(json_path) or {}
        for en_text, target_text in ui_data.items():
            add(en_text, target_text)

    return en_to_lang


def main(inp, outp):
    print(f"Target language: {LANG_NAME} ({DIR_LANG})")
    try:
        gm = bytearray(open(inp, "rb").read())
        sanity, version = struct.unpack_from("<Ii", gm, 0)
    except FileNotFoundError:
        print(f"[!] Input file not found: {inp}")
        sys.exit(1)
    except struct.error:
        print(f"[!] Input file too short or invalid: {inp}")
        sys.exit(1)
    if sanity != 0xFAB11BAF:
        print(f"[!] Not a valid global-metadata.dat file (sanity {sanity:#x}): {inp}")
        sys.exit(1)

    slOff = struct.unpack_from("<I", gm, 8)[0]
    npairs = (slOff - 8) // 8
    pairs = [list(struct.unpack_from("<II", gm, 8 + i * 8)) for i in range(npairs)]
    sldOff, sldSize = pairs[1]

    prot = load_protection(PROTECTION_FILE)

    tr = build_dict()
    print("Master dict (EN -> LANG) entries:", len(tr))
    tr_b = {k.encode(): v.encode() for k, v in tr.items()}

    nlit = pairs[0][1] // 8

    # ---- STEP 0: Read original literals (before any modification) ----
    orig = read_literals(gm)
    assert len(orig) == nlit

    # Positions are only reliable if the JSON was generated from THIS patched EN file.
    if prot:
        bad0 = check_protection(orig, prot)
        if bad0:
            print(f"[!] {len(bad0)} JSON pairs do NOT match the input file "
                  f"(e.g., positions {bad0[:5]}). The JSON was not generated from this "
                  f"patched EN file. Aborting.")
            sys.exit(2)
        print("Input verification OK: all JSON pairs are present in the EN file")

    # ---- STEP 1: INBOUND BLOCKING ----
    # At a protected position, we never translate (the JSON value matches).
    final = []
    done = 0
    blocked = []
    for i, en_b in enumerate(orig):
        if i in prot:
            final.append(prot[i])
            if en_b in tr_b:
                blocked.append((i, en_b))
            continue
        lang_b = tr_b.get(en_b)
        if lang_b is not None:
            final.append(lang_b)
            done += 1
        else:
            final.append(en_b)
    print(f"Translated: {done} | Writes blocked at input (protected position): {len(blocked)}")
    for i, v in blocked[:20]:
        print(f"   [{i}] {v.decode('utf-8', 'replace')!r}")

    # ---- STEP 2: RE-APPLY BEFORE REMAP ----
    reapplied = 0
    for i, v in prot.items():
        if final[i] != v:
            final[i] = v
            reapplied += 1
    if reapplied:
        print(f"Re-applied before remap: {reapplied} protected positions corrected")

    # ---- STEP 3: REMAP (Reconstructing stringLiteralData) ----
    # Only dataIndex/length change: table ORDER (and thus positions
    # referenced by code) remains identical. Value deduplication is performed.
    def build(final_vals):
        blob = bytearray()
        placed = {}
        entries = []  # (nlen, ndi) per position
        for v in final_vals:
            if v in placed:
                ndi, nlen = placed[v]
            else:
                ndi, nlen = len(blob), len(v)
                blob += v
                placed[v] = (ndi, nlen)
            entries.append((nlen, ndi))
        while len(blob) % 4:
            blob.append(0)
        return blob, entries

    def assemble(blob, entries):
        buf = bytearray(gm)
        for i, (nlen, ndi) in enumerate(entries):
            struct.pack_into("<II", buf, slOff + i * 8, nlen, ndi)
        new_size = len(blob)
        d = new_size - sldSize
        prs = [list(p) for p in pairs]
        prs[1][1] = new_size
        for p in prs:
            if p[0] > sldOff:
                p[0] += d
        for i, p in enumerate(prs):
            struct.pack_into("<II", buf, 8 + i * 8, p[0], p[1])
        return bytes(buf[:sldOff]) + bytes(blob) + bytes(buf[sldOff + sldSize:]), new_size, d

    new_blob, entries = build(final)
    out, new_size, delta = assemble(new_blob, entries)

    # ---- STEP 4: FINAL VERIFICATION on produced file, position by position ----
    for attempt in range(1, 4):
        lits_out = read_literals(bytearray(out))
        if len(lits_out) != nlit:
            print(f"[!] ERROR: {len(lits_out)} output literals instead of {nlit}. File NOT written.")
            sys.exit(3)
        bad = check_protection(lits_out, prot)
        if not bad:
            print(f"Final verification OK (attempt {attempt}): {len(prot)} protected positions "
                  f"exactly match their original JSON value")
            break

        ratio = len(bad) / max(1, len(prot))
        if ratio > 0.5:
            print(f"[!] {len(bad)}/{len(prot)} protected positions altered ({ratio:.0%}): "
                  f"Probable GLOBAL SHIFT of positions.")
        else:
            print(f"[!] {len(bad)}/{len(prot)} protected positions altered "
                  f"(e.g., {bad[:8]}).")
        # Repair: force these positions back to the JSON value, then rebuild remap.
        for i in bad:
            final[i] = prot[i]
        new_blob, entries = build(final)
        out, new_size, delta = assemble(new_blob, entries)
    else:
        lits_out = read_literals(bytearray(out))
        bad = check_protection(lits_out, prot)
        if bad:
            print(f"[!] FAILURE: {len(bad)} protected positions still altered after repair. "
                  f"File NOT written.")
            sys.exit(3)

    # ---- STEP 5: GLOBAL CHECK ----
    # Any UNPROTECTED position must equal either the original value or the translated value from the dictionary.
    lits_out = read_literals(bytearray(out))
    anomalies = []
    for i, (o, n) in enumerate(zip(orig, lits_out)):
        if i in prot:
            continue
        if n != o and n != tr_b.get(o):
            anomalies.append(i)
    if anomalies:
        print(f"[!] ERROR: {len(anomalies)} unprotected positions have unexpected values "
              f"(e.g., {anomalies[:8]}). File NOT written.")
        sys.exit(3)
    print("Global check OK: no position differs from original outside of expected translations")

    with open(outp, "wb") as f:
        f.write(out)

    print(f"Translated {done} literals; sldData {sldSize} -> {new_size} (delta {delta:+}); "
          f"filesize {len(gm)} -> {len(out)}; wrote {outp}")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) < 2:
        print("Usage: python patch_global-metadata.dat.py <in> <out> [--lang=LanguageName]")
        sys.exit(1)
    main(args[0], args[1])
